"""empty message

Revision ID: f2ed0eefd049
Revises:
Create Date: 2020-01-11 11:52:08.351892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ed0eefd049'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=False),
                    sa.Column('gender', sa.String(length=20), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_actors'))
                    )
    op.create_table('movies',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('release_date', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_movies')),
                    sa.UniqueConstraint('title', name=op.f('uq_movies_title'))
                    )
    op.create_table('movies_association',
                    sa.Column('actor_id', sa.Integer(), nullable=False),
                    sa.Column('movie_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'],
                                            name=op.f(
                        'fk_movies_association_actor_id_actors')),
                    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'],
                                            name=op.f(
                        'fk_movies_association_movie_id_movies')),
                    sa.PrimaryKeyConstraint('actor_id', 'movie_id',
                                            name=op.f('pk_movies_association'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies_association')
    op.drop_table('movies')
    op.drop_table('actors')
    # ### end Alembic commands ###
